// Integration fixtures use captured responses explicitly; no test is live evidence.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {appService} from '../src/app/service.mjs';
import {intent} from '../src/app/intent.mjs';
import {decision,executionState} from '../src/app/view.mjs';
import {quotePair} from '../src/collect.mjs';
import {bundleSnapshot} from '../src/execution/pipeline.mjs';
const bundle=JSON.parse(readFileSync('evidence/execution/m2a-wallet-attempt4-2026-09-13.json.analysis.json'));
const receipt=JSON.parse(readFileSync('evidence/execution/m2a-wallet-attempt4-2026-09-13.json')).receipt;
const input={underlying:'TSLA',amount:'1',mode:'LIVE'},wallet=receipt.walletPublicKey;
function service(extra={}){return appService({clock:()=>bundle.snapshot.asOfMs,sleep:async()=>{},collector:async()=>structuredClone(bundle.snapshot),load:async()=>structuredClone(bundle),persist:async()=>{},...extra});}
async function analyzed(s,i=input){const j=s.start(i);return s.settled(j.id);}
test('all 160-test baseline files and evidence preserved byte for byte',()=>{for(const [p,h] of Object.entries(JSON.parse(readFileSync('preservation/pre-milestone3-sha256.json'))))assert.equal(createHash('sha256').update(readFileSync(p)).digest('hex'),h,p);});
test('Tesla intent resolves both canonical representations',async()=>{const j=await analyzed(service());assert.deepEqual(j.resolved.map(a=>a.symbol),['TSLAx','TSLAon']);assert.deepEqual(j.resolved.map(a=>a.mint),bundle.snapshot.candidates.map(a=>a.mint));assert.equal(j.intent.amountRaw,'1000000');});
for(const amount of ['0','-1','1e2','0.0000001','NaN',' 1',1])test('invalid amount '+JSON.stringify(amount),()=>assert.throws(()=>intent({...input,amount})));
test('intent prohibits frontend mint and unsupported equities',()=>{assert.throws(()=>intent({...input,mint:wallet}),/INVALID_INTENT/);assert.throws(()=>intent({...input,underlying:'NVDA'}),/UNSUPPORTED_UNDERLYING/);assert.equal(intent({...input,amount:'100.000001'}).amountRaw,'100000001');});
test('strict winner preserves reason codes and maps product state',async()=>{const j=await analyzed(service());assert.equal(j.state,'STRICT_WINNER');assert.deepEqual(j.decision.reasonCodes,bundle.result.reasonCodes);assert.equal(j.decision.winner,'TSLAx');assert.equal(j.decision.executionReadiness.preparationAvailable,true);assert.ok(j.events.some(e=>e.state==='QUOTING'));});
test('closed-market anchor remains explicitly not current fair value',async()=>{const j=await analyzed(service());assert.equal(j.decision.marketState,'UNDERLYING_WEEKEND');assert.equal(j.decision.reference.classification,'LAST_MARKET_REFERENCE');assert.equal(j.decision.reference.isCurrentFairValue,false);});
test('no survivor disables preparation at both service and presentation boundaries',async()=>{const s=service({collector:async()=>{const snapshot=structuredClone(bundle.snapshot);snapshot.candidates[0].quote.raw.outputMint=wallet;return snapshot;}}),j=await analyzed(s);assert.equal(j.state,'NO_VERIFIED_REPRESENTATION');assert.equal(j.decision.executionReadiness.preparationAvailable,false);assert.throws(()=>s.prepare(j.id,{wallet}),/NO_EXECUTABLE_STRICT_WINNER/);});
test('provider exception fails explicitly without replay fallback',async()=>{let loaded=false;const s=service({collector:async()=>{throw Error('RATE_LIMITED');},load:async()=>{loaded=true;return bundle;}}),j=await analyzed(s);assert.equal(j.state,'FAILED');assert.deepEqual(j.reasonCodes,['RATE_LIMITED']);assert.equal(loaded,false);});
test('replay bypasses live providers and retains exact capture provenance',async()=>{let called=false;const s=service({collector:async()=>{called=true;throw Error();}}),j=await analyzed(s,{...input,mode:'REPLAY',captureId:'tesla-1-wallet'});assert.equal(called,false);assert.equal(j.state,'STRICT_WINNER');assert.equal(j.decision.isLive,false);assert.equal(j.decision.asOfMs,bundle.snapshot.asOfMs);assert.equal(j.replay.snapshotSha256,bundle.snapshotSha256);assert.deepEqual(j.decision.reasonCodes,bundle.result.reasonCodes);assert.equal(j.decision.executionReadiness.preparationAvailable,false);assert.throws(()=>s.prepare(j.id,{wallet}),/REPLAY_EXECUTION_DISABLED/);});
test('replay cannot masquerade as a different amount or arbitrary file',async()=>{let j=await analyzed(service(),{...input,amount:'100',mode:'REPLAY',captureId:'tesla-1-wallet'});assert.equal(j.error.code,'REPLAY_INPUT_MISMATCH');j=await analyzed(service(),{...input,mode:'REPLAY',captureId:'../../.env'});assert.equal(j.error.code,'UNKNOWN_CAPTURE');});
test('live mode rejects a synthetic collector result',async()=>{const j=await analyzed(service({collector:async()=>({...structuredClone(bundle.snapshot),mode:'synthetic'})}));assert.equal(j.error.code,'LIVE_SOURCE_MISMATCH');});
test('missing wallet preserves strict result and explicit error',async()=>{const s=service(),j=await analyzed(s);assert.throws(()=>s.prepare(j.id,{}),/WALLET_PUBLIC_KEY_REQUIRED/);assert.equal(s.get(j.id).state,'STRICT_WINNER');assert.throws(()=>s.prepare(j.id,{wallet:'not a wallet'}),/INVALID_WALLET_PUBLIC_KEY/);});
test('execution preparation reuses pipeline and maps unfunded simulation blocker',async()=>{let received;const s=service({executor:options=>{assert.equal(options.allowBroadcast,false);return {prepare:async(b,w)=>{received={b,w};return structuredClone(receipt);}};}}),j=await analyzed(s);s.prepare(j.id,{wallet});const done=await s.settled(j.id);assert.equal(received.w,wallet);assert.equal(received.b.snapshotSha256,bundle.snapshotSha256);assert.equal(done.state,'SIMULATION_BLOCKED');assert.deepEqual(done.reasonCodes,receipt.reasonCodes);assert.equal(done.execution.inspection.verified,true);assert.equal(done.execution.signature,null);assert.ok(done.events.some(e=>e.state==='READY_FOR_EXECUTION'));});
test('material-change block requires fresh review',async()=>{const s=service({executor:()=>({prepare:async()=>({...receipt,reasonCodes:['EXECUTION_MATERIALLY_CHANGED'],materialChange:null})})}),j=await analyzed(s);s.prepare(j.id,{wallet});const done=await s.settled(j.id);assert.equal(done.state,'EXECUTION_CHANGED');assert.throws(()=>s.prepare(j.id,{wallet}),/NO_EXECUTABLE_STRICT_WINNER/);});
test('execution readiness never exposes signing or broadcasting',()=>{assert.equal(decision(bundle,'LIVE').executionReadiness.signingAvailable,false);assert.equal(executionState({status:'READY_FOR_SIGNATURE',reasonCodes:[]}),'READY_FOR_SIGNATURE');});
test('concurrent quote requests map reversed arrival to canonical candidates',async()=>{const waiting=[];const http={get:(id,url)=>new Promise(resolve=>waiting.push({id,url,resolve}))};const promise=quotePair(http,bundle.snapshot.order,{clock:()=>bundle.snapshot.asOfMs});assert.equal(waiting.length,2);waiting[1].resolve({id:waiting[1].id,startedAt:1,receivedAt:2,data:{outputMint:bundle.snapshot.candidates[1].mint}});waiting[0].resolve({id:waiting[0].id,startedAt:1,receivedAt:3,data:{outputMint:bundle.snapshot.candidates[0].mint}});const rows=await promise;assert.deepEqual(rows.map(r=>r.symbol),['TSLAx','TSLAon']);for(const row of rows)assert.equal(row.mint,row.quote.raw.outputMint);});
test('candidate view maps gate results by symbol when arrival order differs',()=>{const b=structuredClone(bundle);b.snapshot.candidates.reverse();const v=decision(b,'LIVE');for(const c of v.candidates)assert.deepEqual(c.reasonCodes,b.result.candidates.find(r=>r.symbol===c.symbol).reasonCodes);});
