import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fixture,buildFixture,harness,wallet,asset,testKey} from '../fixtures/execution.mjs';
import {materialGuard,validateQuote} from '../src/execution/guard.mjs';
import {inspectBuild,decodeRoute,construct,signedTransaction} from '../src/execution/transaction.mjs';
import {sealReceipt,replayReceipt} from '../src/execution/receipt.mjs';
test('preserves every original engine, test, fixture and capture byte',()=>{for(const [p,h] of Object.entries(JSON.parse(readFileSync('preservation/pre-execution-sha256.json'))))assert.equal(createHash('sha256').update(readFileSync(p)).digest('hex'),h,p);});
for(const [name,bps,allowed] of [['within tolerance',20,true],['improvement',-100,true],['material degradation',100,false]])test('final requote '+name,()=>{const a=fixture(),q=structuredClone(a.snapshot.candidates[0].quote);q.raw.outAmount=String(BigInt(q.raw.outAmount)*BigInt(10000-bps)/10000n);q.raw.otherAmountThreshold=String(BigInt(q.raw.outAmount)*9950n/10000n);const run=()=>materialGuard(a,a,q,a.snapshot.asOfMs);if(allowed)assert.equal(run().allowed,true);else assert.throws(run,/EXECUTION_MATERIALLY_CHANGED/);});
test('stale final quote blocked',()=>{const a=fixture(),q=structuredClone(a.snapshot.candidates[0].quote);q.startedAt-=20000;assert.throws(()=>materialGuard(a,a,q,a.snapshot.asOfMs),/QUOTE_EXPIRED/);});
test('wrong mint blocked',()=>{const a=fixture(),q=structuredClone(a.snapshot.candidates[0].quote);q.raw.outputMint=wallet;assert.throws(()=>validateQuote(q,asset,a.snapshot.order.amountRaw,a.snapshot.asOfMs),/UNVERIFIED_EXECUTION_MINT/);});
test('price impact blocked',()=>{const a=fixture(),q=structuredClone(a.snapshot.candidates[0].quote);q.raw.priceImpactPct='0.02';assert.throws(()=>validateQuote(q,asset,a.snapshot.order.amountRaw,a.snapshot.asOfMs),/PRICE_IMPACT_LIMIT/);});
test('Token-2022 route is inspected and constructed',()=>{const b=buildFixture();assert.equal(inspectBuild(b,wallet,asset,b.inAmount).tokenProgram,'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb');assert.equal(construct(b,wallet,'11111111111111111111111111111111').message.header.numRequiredSignatures,1);});
for(const [name,change,error] of [['wrong destination',b=>b.swapInstruction.accounts[2].pubkey=wallet,/ACCOUNT_MISMATCH/],['extra signer',b=>b.swapInstruction.accounts[3].isSigner=true,/SIGNER_MISMATCH/],['untrusted program',b=>b.swapInstruction.programId=wallet,/UNTRUSTED/],['extra instruction',b=>b.otherInstructions=[{}],/UNSUPPORTED/],['changed amount',b=>b.inAmount='1',/AMOUNT_MISMATCH/]])test(name,()=>{const b=buildFixture();change(b);assert.throws(()=>inspectBuild(b,wallet,asset,b.inAmount),error);});
test('truncated instruction rejected',()=>assert.throws(()=>decodeRoute(buildFixture().swapInstruction.data.slice(0,24))));
test('wallet signature binds exact message',()=>{const b=buildFixture(),tx=construct(b,wallet,'11111111111111111111111111111111');tx.sign([testKey]);assert.doesNotThrow(()=>signedTransaction(Buffer.from(tx.serialize()).toString('base64'),tx,wallet));const other=construct(b,wallet,wallet);assert.throws(()=>signedTransaction(Buffer.from(tx.serialize()).toString('base64'),other,wallet),/SIGNED_TRANSACTION_CHANGED/);});
for(const [name,options,expected,code] of [['success',{},'SUCCEEDED','RECEIVED_AMOUNT_VERIFIED'],['simulation failure',{simFail:true},'BLOCKED','TRANSACTION_SIMULATION_FAILED'],['unfunded wallet',{unfunded:true},'BLOCKED','INSUFFICIENT_USDC'],['wallet rejection',{reject:true},'BLOCKED','USER_SIGNATURE_REJECTED'],['broadcast uncertainty',{broadcastFail:true},'BROADCAST_UNKNOWN','TRANSACTION_BROADCAST_FAILED'],['below protected minimum',{below:true},'CONFIRMED_BELOW_MINIMUM','RECEIVED_AMOUNT_BELOW_MINIMUM']])test('pipeline '+name,async()=>{
 const h=harness(options),r=await h.pipeline.prepare(h.analysis,wallet);if(r.status==='READY_FOR_SIGNATURE')await h.pipeline.submit(r,{signTransaction:h.signTransaction,authorizeBroadcast:true});assert.equal(r.status,expected,JSON.stringify(r.reasonCodes));assert.ok(r.reasonCodes.includes(code));assert.equal(replayReceipt(sealReceipt(r)).status,expected);if(options.unfunded||options.simFail){assert.ok(h.calls.includes('simulateTransaction'));assert.ok(!h.calls.includes('sendTransaction'));assert.equal(r.signature,null);}
});
test('broadcast requires explicit authorization',async()=>{const h=harness(),r=await h.pipeline.prepare(h.analysis,wallet);await h.pipeline.submit(r,{signTransaction:h.signTransaction});assert.ok(r.reasonCodes.includes('BROADCAST_NOT_AUTHORIZED'));assert.ok(!h.calls.includes('sendTransaction'));});
test('modified prepared receipt cannot execute',async()=>{const h=harness(),r=await h.pipeline.prepare(h.analysis,wallet);r.inputAmount='1';await h.pipeline.submit(r,{signTransaction:h.signTransaction,authorizeBroadcast:true});assert.ok(r.reasonCodes.includes('EXECUTION_ALREADY_USED_OR_BLOCKED'));});
test('receipt byte tampering rejected',async()=>{const h=harness(),r=await h.pipeline.prepare(h.analysis,wallet),b=sealReceipt(r);b.receipt.status='SUCCEEDED';assert.throws(()=>replayReceipt(b),/HASH_MISMATCH/);});
test('RPC failure prevents signing',async()=>{const h=harness({rpcFailure:'getLatestBlockhash'}),r=await h.pipeline.prepare(h.analysis,wallet);assert.equal(r.status,'BLOCKED');assert.ok(!h.calls.includes('sendTransaction'));});

// Jupiter uses checked_ceil_div for the integer protected minimum (official aggregator audit).
test('Jupiter ceiling minimum preserves every protected raw token unit',()=>{const b=buildFixture();b.outAmount='275147';b.otherAmountThreshold='273772';const bytes=Buffer.from(b.swapInstruction.data,'base64');bytes.writeBigUInt64LE(275147n,16);b.swapInstruction.data=bytes.toString('base64');assert.doesNotThrow(()=>inspectBuild(b,wallet,asset,b.inAmount));b.otherAmountThreshold='273773';assert.throws(()=>inspectBuild(b,wallet,asset,b.inAmount),/UNPROTECTED_MINIMUM_OUTPUT/);});
