const $=id=>document.getElementById(id);let csrf='',current=null,generation=0,catalog=[];
const terminal=new Set(['STRICT_WINNER','NO_VERIFIED_REPRESENTATION','READY_FOR_SIGNATURE','SIMULATION_BLOCKED','EXECUTION_CHANGED','FAILED','CONFIRMED']);
const stamp=ms=>Number.isFinite(ms)?new Date(ms).toISOString():'Unavailable';
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Stocklana-Token':csrf},body:JSON.stringify(body)}:{});const b=await r.json();if(!r.ok)throw Error(b.error?.code??'REQUEST_FAILED');return b;}
function mode(){const replay=$('mode').value==='REPLAY';$('capture-label').hidden=!replay;$('amount').disabled=replay;$('mode-label').className=replay?'replay':'';$('mode-label').textContent=replay?'REPLAY · Historical evidence. Execution is disabled.':'LIVE · Current providers. No fallback to replay.';if(replay){const c=catalog.find(c=>c.id===$('capture').value);if(c)$('amount').value=String(Number(c.amountRaw)/1e6);}current=null;$('prepare').disabled=true;$('analysis').hidden=true;$('execution').hidden=true;$('status').textContent='IDLE';generation++;}
function eligibility(){const ready=current?.state==='STRICT_WINNER'&&current.decision?.executionReadiness.preparationAvailable;const wallet=$('wallet').value.trim();$('prepare').disabled=!ready||!wallet;$('prepare-help').textContent=!ready?(current?.execution?'Preparation ended with '+current.state+'. Run a new analysis before retrying.':current?.state==='REQUOTING'?'Preparation is in progress.':'A live strict winner is required.'):!wallet?'Enter a public wallet address to prepare.':'Preparation obtains a fresh comparison and wallet-bound quote before inspection and simulation.';}
function render(j){current=j;$('status').textContent=j.state;$('history').textContent=JSON.stringify(j.events,null,2);$('error').textContent=j.error?.code??'';
 if(j.decision){const d=j.decision;$('analysis').hidden=false;$('winner').textContent=d.winner?'Strict winner: '+d.winner:'No verified representation — preparation unavailable.';$('session').textContent='Underlying market: '+d.marketState+' · '+d.executionClassification;$('reference').textContent='Reference: '+d.reference?.classification+' · '+(d.reference?.isCurrentFairValue?'Current reference':'Economic anchor only; not current fair value')+' · age at analysis: '+(d.reference?.ageMs==null?'unknown':Math.round(d.reference.ageMs/1000)+' seconds');$('asof').textContent=(j.intent.mode==='REPLAY'?'Historical capture: ':'Live analysis captured: ')+stamp(d.asOfMs);$('readiness').textContent=j.state==='STRICT_WINNER'&&d.executionReadiness.preparationAvailable?'Strict decision passed. Wallet-bound preparation is available; this is not an executed trade.':'Preparation status: '+j.state+'. No trade has been executed.';
 $('candidates').replaceChildren();for(const c of d.candidates){const tr=document.createElement('tr');const values=[c.symbol+' / '+c.issuer,c.eligible?'Verified candidate':'Excluded',c.minimumOutputRaw??'Unavailable',c.economicExposure?.minimumShares??'Unavailable'];for(const v of values){const td=document.createElement('td');td.textContent=v;tr.append(td);}const td=document.createElement('td'),detail=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=c.reasonCodes.join(', ')||'Inspect gates';pre.textContent=JSON.stringify({mint:c.mint,identityVerified:c.identityVerified,quoteStartedAt:stamp(c.quote?.startedAt),quoteReceivedAt:stamp(c.quote?.receivedAt),minimumOutputUnit:'raw token units',economicExposure:c.economicExposure,gates:c.gates},null,2);detail.append(summary,pre);td.append(detail);tr.append(td);$('candidates').append(tr);}
 $('decision-details').textContent=JSON.stringify({reasonCodes:d.reasonCodes,exclusions:d.exclusions,comparisonGates:d.comparisonGates},null,2);$('provenance').textContent=JSON.stringify({mode:d.mode,replay:j.replay,collectionTiming:j.collectionTiming,references:d.references,reference:d.reference,evidence:d.evidence},null,2);
 }
 if(j.execution){const e=j.execution;$('execution').hidden=false;$('execution-state').textContent=j.state+' · '+e.reasonCodes.join(', ');$('material').textContent=e.materialChange?'Final requote: '+e.materialChange.reasonCodes.join(', ')+' · degradation '+e.materialChange.degradationBps+' bps · protected minimum '+e.materialChange.finalMinimumOutput+' raw units':'Final requote has not passed.';$('funds').textContent=e.preBalances?'Source USDC balance: '+e.preBalances.input+' raw units · SOL: '+e.preBalances.solLamports+' lamports. No funds were spent.':'Balances not reached.';$('execution-details').textContent=JSON.stringify(e,null,2);}
 eligibility();}
async function poll(j,g){if(g!==generation)return;render(j);while(!terminal.has(j.state)){await new Promise(r=>setTimeout(r,700));if(g!==generation)return;j=await api('/api/jobs/'+j.id);if(g!==generation)return;render(j);}}
$('intent').addEventListener('submit',async event=>{event.preventDefault();const g=++generation;current=null;$('error').textContent='';$('analysis').hidden=true;$('execution').hidden=true;$('prepare').disabled=true;$('analyze').disabled=true;$('status').textContent='RESOLVING';try{const j=await api('/api/analyses',{underlying:'TSLA',amount:$('amount').value,mode:$('mode').value,...($('mode').value==='REPLAY'?{captureId:$('capture').value}:{})});if(g===generation)await poll(j,g);}catch(e){$('error').textContent=e.message;$('status').textContent='FAILED';}finally{$('analyze').disabled=false;}});
$('prepare').addEventListener('click',async()=>{const g=++generation;$('prepare').disabled=true;$('error').textContent='';try{await poll(await api('/api/jobs/'+current.id+'/prepare',{wallet:$('wallet').value.trim()}),g);}catch(e){$('error').textContent=e.message;eligibility();}});
$('mode').addEventListener('change',mode);$('capture').addEventListener('change',mode);$('wallet').addEventListener('input',eligibility);$('amount').addEventListener('input',()=>{generation++;current=null;$('analysis').hidden=true;$('execution').hidden=true;$('status').textContent='IDLE';eligibility();});
try{const b=await api('/api/bootstrap');csrf=b.csrfToken;catalog=b.captures;for(const c of catalog){const option=document.createElement('option');option.value=c.id;option.textContent=c.label+' · '+stamp(c.asOfMs);$('capture').append(option);}}catch(e){$('error').textContent=e.message;$('analyze').disabled=true;}
